name: panache_core
description: Panache app core
version: 0.1.0
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/panache

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: 1.1.0
  path_provider: 2.0.2
  string_scanner: 1.1.0
  http: 0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - logo.png