name: flutterial
description: Flutter Material Theme explorer
version: 0.0.1
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/flutterial

dependencies:
  flutter:
    sdk: flutter
  flutterial_components:
    #git: https://github.com/rxlabz/flutterial_components
    path: /Users/rxlabz/tmp/flutterial_components/

flutter:
  uses-material-design: true
  assets:
      - assets/theme.json
