name: panache
description: Flutter Material Theme editor
version: 0.1.0
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/panache

dependencies:
  flutter:
    sdk: flutter
  panache_lib:
    git: https://github.com/rxlabz/panache_lib
  scoped_model: ^1.0.1
  string_scanner: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter:
  uses-material-design: true
