name: flutterial
description: Flutter Material Theme explorer
version: 0.0.1
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/flutterial

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  flutterial_components:
    path: /Users/rxlabz/dev/projects/flutterial_components

flutter:
  uses-material-design: true
  assets:
      - assets/theme.json
